import SwiftUI

// First-launch onboarding, three steps: pick a camera, calibrate (voice-guided,
// hold-still to lock each side), then fit the HRTF while a guide voice loops
// ahead-and-slightly-right. The spoken cues are bundled per-language
// (Resources/onboarding, generated by tools/gen-onboarding-voices.py) and play
// through the engine's audition source, so the acoustics ARE the product demo.

// MARK: - shared chrome

private func stepDots(_ current: Int) -> some View {
    HStack(spacing: 6) {
        ForEach(1...3, id: \.self) { i in
            Circle()
                .fill(.white.opacity(i == current ? 0.85 : 0.22))
                .frame(width: 6, height: 6)
        }
    }
}

private struct OnboardCard: ViewModifier {
    func body(content: Content) -> some View {
        content
            .padding(28)
            .frame(width: 440)
            .background(Color.white.opacity(0.04))
            .clipShape(RoundedRectangle(cornerRadius: 18))
            .overlay(RoundedRectangle(cornerRadius: 18).stroke(.white.opacity(0.08)))
            .fontDesign(.rounded)
    }
}

// MARK: - step 1: camera

struct CameraStepView: View {
    @ObservedObject var tracker: FaceTracker
    let onDone: () -> Void
    @ObservedObject private var i18n = I18n.shared

    var body: some View {
        VStack(spacing: 16) {
            stepDots(1)
            Text(L("Camera")).font(.title2.weight(.semibold))
            Text(L("Pick the camera that watches you."))
                .font(.callout).foregroundStyle(.secondary)
            CameraPreview(session: tracker.session)
                .aspectRatio(tracker.imageAspect, contentMode: .fit)
                .frame(maxWidth: 340, maxHeight: 255)
                .clipShape(RoundedRectangle(cornerRadius: 10))
            if tracker.devices.count > 1 {
                Picker("", selection: Binding(
                    get: { tracker.selectedID },
                    set: { id in tracker.selectedID = id; tracker.switchTo(id) })) {
                    ForEach(tracker.devices) { d in Text(d.name).tag(d.id) }
                }
                .labelsHidden().frame(maxWidth: 300)
            }
            Text(tracker.faceFound ? L("Head tracking ready") : L("Looking for your face…"))
                .font(.caption)
                .foregroundStyle(tracker.faceFound ? .green : .secondary)
            Button(L("Continue")) { onDone() }
                .buttonStyle(.borderedProminent)
                .disabled(!tracker.faceFound)
        }
        .modifier(OnboardCard())
    }
}

// MARK: - step 2: calibration (voice-guided, hold-still locks)

struct CalibrationStepView: View {
    @ObservedObject var tracker: FaceTracker
    let engine: ChamberEngine
    /// Shown as step 2 of 3 during onboarding; standalone (no dots) on recalibrate.
    var standalone = false
    let onDone: () -> Void
    @ObservedObject private var i18n = I18n.shared

    private enum Phase { case left, right, done }
    @State private var phase: Phase = .left
    @State private var yaw0 = 0.0 // where the head was when the step began
    @State private var leftYaw = 0.0
    @State private var leftPitch = 0.0
    @State private var holdAnchor = Double.nan
    @State private var holdStart = 0.0
    @State private var holdFrac = 0.0

    private let holdSecs = 1.0
    private let turnMin = rad(10) // must actually turn away from the start pose
    private let stillTol = rad(2.5) // "within reason" — the 1€ filter helps

    private let tick = Timer.publish(every: 0.05, on: .main, in: .common).autoconnect()

    var body: some View {
        VStack(spacing: 16) {
            if !standalone { stepDots(2) }
            Text(arrow).font(.system(size: 76, weight: .thin))
            Text(cueText).font(.title3)
                .multilineTextAlignment(.center)
                .fixedSize(horizontal: false, vertical: true)
            // the hold-still lock: fills while the head stays put
            GeometryReader { geo in
                ZStack(alignment: .leading) {
                    Capsule().fill(.white.opacity(0.1))
                    Capsule().fill(Color(hex: "#5fd0c5").opacity(0.8))
                        .frame(width: geo.size.width * holdFrac)
                }
            }
            .frame(width: 220, height: 5)
            .opacity(phase == .done ? 0 : 1)
            if holdFrac > 0, phase != .done {
                Text(L("Hold still…")).font(.caption).foregroundStyle(.secondary)
            }
            if phase != .done {
                Button(L("Skip")) { finish(calibrated: false) }
                    .buttonStyle(.borderless).font(.caption).foregroundStyle(.secondary)
            }
        }
        .modifier(OnboardCard())
        .onAppear {
            yaw0 = tracker.yaw
            engine.onboardPlay("cal_left")
        }
        .onReceive(tick) { _ in step() }
    }

    private var arrow: String {
        switch phase {
        case .left: return "←"
        case .right: return "→"
        case .done: return "✓"
        }
    }

    private var cueText: String {
        switch phase {
        case .left: return L("Turn your head all the way to the left… and hold still.")
        case .right: return L("Now all the way to the right… and hold still.")
        case .done: return L("Done. You're calibrated.")
        }
    }

    private func step() {
        guard phase != .done else { return }
        let now = CACurrentMediaTime()
        let yaw = tracker.yaw
        let dev = yaw - yaw0
        var turned = abs(dev) > turnMin && tracker.faceFound
        if phase == .right {
            // must be on the OTHER side of where the left lock landed
            turned = turned && ((dev >= 0) != (leftYaw - yaw0 >= 0))
        }
        guard turned else { holdAnchor = .nan; holdFrac = 0; return }
        if holdAnchor.isNaN || abs(yaw - holdAnchor) > stillTol {
            holdAnchor = yaw
            holdStart = now
            holdFrac = 0
            return
        }
        holdFrac = min(1, (now - holdStart) / holdSecs)
        if holdFrac >= 1 { lock(yaw: yaw) }
    }

    private func lock(yaw: Double) {
        switch phase {
        case .left:
            leftYaw = yaw
            leftPitch = tracker.pitch
            phase = .right
            holdAnchor = .nan
            holdFrac = 0
            engine.onboardPlay("cal_right")
        case .right:
            tracker.calibrate(yawLeftRad: leftYaw, yawRightRad: yaw,
                              neutralPitchRad: (leftPitch + tracker.pitch) / 2)
            finish(calibrated: true)
        case .done:
            break
        }
    }

    private func finish(calibrated: Bool) {
        phase = .done
        if calibrated {
            tracker.resetNeutral()
            tracker.persistCalibration()
            engine.onboardPlay("cal_done")
            DispatchQueue.main.asyncAfter(deadline: .now() + 2.2) { onDone() }
        } else {
            engine.onboardStop()
            onDone()
        }
    }
}

// MARK: - step 3: fit

struct FitStepView: View {
    @ObservedObject var engine: ChamberEngine
    let onDone: () -> Void
    @ObservedObject private var i18n = I18n.shared

    var body: some View {
        VStack(spacing: 16) {
            stepDots(3)
            Text(L("Fit")).font(.title2.weight(.semibold))
            Text(L("Move the slider until my voice sits just ahead of you, out in the room."))
                .font(.callout).foregroundStyle(.secondary)
                .multilineTextAlignment(.center)
                .fixedSize(horizontal: false, vertical: true)
            HStack(spacing: 10) {
                Slider(value: Binding(get: { engine.freqScale },
                                      set: { engine.setFreqScale($0) }), in: 0.7...2.2)
                    .frame(width: 260)
                Text(String(format: "%.2f", engine.freqScale))
                    .font(.caption.monospacedDigit()).foregroundStyle(.secondary)
            }
            Button(L("Continue")) { onDone() }
                .buttonStyle(.borderedProminent)
        }
        .modifier(OnboardCard())
        // the guide voice loops from ahead-and-slightly-right the whole step
        .onAppear { engine.onboardPlay("fit", loop: true, bearingDeg: 15) }
        .onDisappear { engine.onboardStop() }
    }
}
