import SwiftUI

// First-launch onboarding, three steps: pick a camera, calibrate (voice-guided,
// hold-still to lock each side), then fit the HRTF while a guide voice loops
// ahead-and-slightly-right. The spoken cues are bundled per-language
// (Resources/onboarding, generated by tools/gen-onboarding-voices.py) and play
// through the engine's audition source, so the acoustics ARE the product demo.

// MARK: - Antiphon brand (tokens from the marketing-site handoff)

enum AN {
    static let cream = Color(red: 0.984, green: 0.969, blue: 0.941)      // #FBF7F0
    static let warm = Color(red: 0.957, green: 0.929, blue: 0.886)       // #F4EDE2
    static let ink = Color(red: 0.165, green: 0.137, blue: 0.106)        // #2A231B
    static let secondary = Color(red: 0.420, green: 0.373, blue: 0.318)  // #6B5F51
    static let muted = Color(red: 0.639, green: 0.588, blue: 0.518)      // #A39684
    static let cobalt = Color(red: 0.153, green: 0.263, blue: 0.722)     // #2743B8
    static let terracotta = Color(red: 0.769, green: 0.412, blue: 0.290) // #C4694A
}

/// The concentric-circle mati eye (hero proportions from the handoff), with an
/// optional pupil offset so it can watch the cursor.
struct AntiphonEye: View {
    var size: CGFloat
    var pupil: CGSize = .zero
    var body: some View {
        let k = size / 220
        ZStack {
            Circle().fill(AN.cream)
                .overlay(Circle().stroke(AN.cobalt, lineWidth: 2.5 * k))
            Circle().fill(AN.cobalt).frame(width: 176 * k, height: 176 * k)
            Circle().fill(AN.cream).frame(width: 120 * k, height: 120 * k)
            ZStack {
                Circle().fill(AN.ink).frame(width: 60 * k, height: 60 * k)
                Circle().fill(AN.cream).opacity(0.9)
                    .frame(width: 14 * k, height: 14 * k)
                    .offset(x: -10 * k, y: -10 * k)
            }
            .offset(pupil)
        }
        .frame(width: size, height: size)
    }
}

/// The site's pill button: cobalt fill, cream text.
private struct PillButtonStyle: ButtonStyle {
    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .font(.system(size: 15, weight: .semibold))
            .foregroundStyle(AN.cream)
            .padding(.vertical, 13).padding(.horizontal, 30)
            .background(Capsule().fill(AN.cobalt.opacity(configuration.isPressed ? 0.85 : 1)))
    }
}

// MARK: - shared chrome

private func stepDots(_ current: Int) -> some View {
    HStack(spacing: 6) {
        ForEach(1...2, id: \.self) { i in
            Circle()
                .fill(.white.opacity(i == current ? 0.85 : 0.22))
                .frame(width: 6, height: 6)
        }
    }
}

// MARK: - the welcome (one full-bleed screen: brand + requirements + camera)

struct WelcomeView: View {
    @ObservedObject var tracker: FaceTracker
    @ObservedObject var engine: ChamberEngine
    let enabled: Bool
    let onEnable: () -> Void
    let onStart: () -> Void   // saved calibration: straight into the room
    let onSetUp: () -> Void   // begin (or redo) calibration
    @ObservedObject private var i18n = I18n.shared
    @State private var pupil: CGSize = .zero

    var body: some View {
        GeometryReader { geo in
            ZStack {
                AN.cream.ignoresSafeArea()
                VStack(spacing: 0) {
                    Spacer(minLength: 24)
                    AntiphonEye(size: 130, pupil: pupil)
                        .animation(.easeOut(duration: 0.18), value: pupil)
                        .padding(.bottom, 26)
                    Text("Antiphon")
                        .font(.system(size: 40, design: .serif))
                        .foregroundStyle(AN.ink)
                        .padding(.bottom, 10)
                    Text(L("Your agents, speaking. You, listening."))
                        .font(.system(size: 21, design: .serif))
                        .foregroundStyle(AN.ink.opacity(0.85))
                        .padding(.bottom, 8)
                    Text(L("Antiphon gives every coding agent a voice, placed in the room around you. Put on headphones and overhear the work."))
                        .font(.system(size: 14))
                        .foregroundStyle(AN.secondary)
                        .multilineTextAlignment(.center)
                        .frame(maxWidth: 440)
                        .fixedSize(horizontal: false, vertical: true)
                        .padding(.bottom, 26)

                    if !enabled {
                        Button(L("Enable camera & continue")) { onEnable() }
                            .buttonStyle(PillButtonStyle())
                        Text(L("Turn your head to face agents. Video never leaves your device."))
                            .font(.system(size: 12)).foregroundStyle(AN.muted)
                            .padding(.top, 12)
                    } else {
                        // the camera step, unified into the welcome — no mirror:
                        // nobody needs to see their own face, just pick + confirm
                        if tracker.devices.count > 1 {
                            Picker("", selection: Binding(
                                get: { tracker.selectedID },
                                set: { id in tracker.selectedID = id; tracker.switchTo(id) })) {
                                ForEach(tracker.devices) { d in Text(d.name).tag(d.id) }
                            }
                            .labelsHidden().frame(maxWidth: 260)
                            .padding(.bottom, 10)
                        }
                        HStack(spacing: 7) {
                            Image(systemName: tracker.faceFound ? "checkmark.circle.fill" : "circle.dashed")
                                .font(.system(size: 13))
                            Text(tracker.faceFound
                                ? (tracker.hasSavedCalibration ? L("Calibration restored") : L("Head tracking ready"))
                                : L("Looking for your face…"))
                                .font(.system(size: 12.5))
                        }
                        .foregroundStyle(tracker.faceFound ? AN.cobalt : AN.muted)
                        .padding(.bottom, 16)
                        if tracker.hasSavedCalibration {
                            Button(L("Start")) { onStart() }
                                .buttonStyle(PillButtonStyle())
                                .disabled(!tracker.faceFound)
                            Button(L("Set up again")) { onSetUp() }
                                .buttonStyle(.plain)
                                .font(.system(size: 12.5))
                                .foregroundStyle(AN.cobalt)
                                .padding(.top, 10)
                        } else {
                            Button(L("Continue")) { onSetUp() }
                                .buttonStyle(PillButtonStyle())
                                .disabled(!tracker.faceFound)
                        }
                    }

                    Spacer(minLength: 24)
                    Text(L("By Caleb Foust"))
                        .font(.system(size: 11))
                        .foregroundStyle(AN.muted)
                        .padding(.bottom, 16)
                }
                .frame(maxWidth: .infinity)
            }
            // the window runs dark; this screen is cream — restyle the native
            // controls (picker!) for a light ground or they render white-on-cream
            .environment(\.colorScheme, .light)
            // the eye watches the cursor (hero behavior: max ±22 pt, full
            // deflection beyond ~300 pt — measured from the eye's spot)
            .onContinuousHover { phase in
                switch phase {
                case .active(let p):
                    let eye = CGPoint(x: geo.size.width / 2, y: geo.size.height * 0.22)
                    let dx = p.x - eye.x, dy = p.y - eye.y
                    let dist = max(sqrt(dx * dx + dy * dy), 1)
                    let mag = min(dist / 300, 1) * 13 // scaled for the 130 pt eye
                    pupil = CGSize(width: dx / dist * mag, height: dy / dist * mag)
                case .ended:
                    pupil = .zero
                }
            }
        }
    }
}

private struct OnboardCard: ViewModifier {
    func body(content: Content) -> some View {
        content
            .padding(28)
            .frame(width: 440)
            .background(Color.white.opacity(0.04))
            .clipShape(RoundedRectangle(cornerRadius: 18))
            .overlay(RoundedRectangle(cornerRadius: 18).stroke(.white.opacity(0.08)))
            .fontDesign(.rounded)
    }
}

// MARK: - step 1: calibration (voice-guided, hold-still locks)

struct CalibrationStepView: View {
    @ObservedObject var tracker: FaceTracker
    let engine: ChamberEngine
    /// Shown as step 1 of 2 during onboarding; standalone (no dots) on recalibrate.
    var standalone = false
    let onDone: () -> Void
    @ObservedObject private var i18n = I18n.shared

    private enum Phase { case left, right, done }
    @State private var phase: Phase = .left
    @State private var yaw0 = 0.0 // where the head was when the step began
    @State private var leftYaw = 0.0
    @State private var leftPitch = 0.0
    @State private var holdAnchor = Double.nan
    @State private var holdStart = 0.0
    @State private var holdFrac = 0.0

    private let holdSecs = 1.0
    private let turnMin = rad(10) // must actually turn away from the start pose
    private let stillTol = rad(2.5) // "within reason" — the 1€ filter helps

    var body: some View {
        VStack(spacing: 16) {
            if !standalone { stepDots(1) }
            Text(arrow).font(.system(size: 76, weight: .thin))
            Text(cueText).font(.title3)
                .multilineTextAlignment(.center)
                .fixedSize(horizontal: false, vertical: true)
            // the hold-still lock: fills while the head stays put
            GeometryReader { geo in
                ZStack(alignment: .leading) {
                    Capsule().fill(.white.opacity(0.1))
                    Capsule().fill(Color(hex: "#5fd0c5").opacity(0.8))
                        .frame(width: geo.size.width * holdFrac)
                }
            }
            .frame(width: 220, height: 5)
            .opacity(phase == .done ? 0 : 1)
            if holdFrac > 0, phase != .done {
                Text(L("Hold still…")).font(.caption).foregroundStyle(.secondary)
            }
            if phase != .done {
                Button(L("Skip")) { finish(calibrated: false) }
                    .buttonStyle(.borderless).font(.caption).foregroundStyle(.secondary)
            }
        }
        .modifier(OnboardCard())
        .onAppear {
            yaw0 = tracker.yaw
            engine.onboardPlay("cal_left")
        }
        // Driven by the pose stream itself — NOT a view-owned Timer: observing
        // the tracker re-renders this view at camera rate, and a re-created
        // Timer.publish would be re-subscribed (and its pending tick killed)
        // on every render, so it never fires even once.
        .onReceive(tracker.$yaw) { _ in step() }
    }

    private var arrow: String {
        switch phase {
        case .left: return "←"
        case .right: return "→"
        case .done: return "✓"
        }
    }

    private var cueText: String {
        switch phase {
        case .left: return L("Turn your head all the way to the left… and hold still.")
        case .right: return L("Now all the way to the right… and hold still.")
        case .done: return L("Done. You're calibrated.")
        }
    }

    private func step() {
        guard phase != .done else { return }
        let now = CACurrentMediaTime()
        let yaw = tracker.yaw
        let dev = yaw - yaw0
        var turned = abs(dev) > turnMin && tracker.faceFound
        if phase == .right {
            // must be on the OTHER side of where the left lock landed
            turned = turned && ((dev >= 0) != (leftYaw - yaw0 >= 0))
        }
        guard turned else { holdAnchor = .nan; holdFrac = 0; return }
        if holdAnchor.isNaN || abs(yaw - holdAnchor) > stillTol {
            holdAnchor = yaw
            holdStart = now
            holdFrac = 0
            return
        }
        holdFrac = min(1, (now - holdStart) / holdSecs)
        if holdFrac >= 1 { lock(yaw: yaw) }
    }

    private func lock(yaw: Double) {
        switch phase {
        case .left:
            leftYaw = yaw
            leftPitch = tracker.pitch
            phase = .right
            holdAnchor = .nan
            holdFrac = 0
            engine.onboardPlay("cal_right")
        case .right:
            tracker.calibrate(yawLeftRad: leftYaw, yawRightRad: yaw,
                              neutralPitchRad: (leftPitch + tracker.pitch) / 2)
            finish(calibrated: true)
        case .done:
            break
        }
    }

    private func finish(calibrated: Bool) {
        phase = .done
        if calibrated {
            tracker.resetNeutral()
            tracker.persistCalibration()
            engine.onboardPlay("cal_done")
            DispatchQueue.main.asyncAfter(deadline: .now() + 2.2) { onDone() }
        } else {
            engine.onboardStop()
            onDone()
        }
    }
}

// MARK: - step 2: fit

struct FitStepView: View {
    @ObservedObject var engine: ChamberEngine
    let onDone: () -> Void
    @ObservedObject private var i18n = I18n.shared

    var body: some View {
        VStack(spacing: 16) {
            stepDots(2)
            Text(L("Fit")).font(.title2.weight(.semibold))
            Text(L("Move the slider until my voice sits just ahead of you, out in the room."))
                .font(.callout).foregroundStyle(.secondary)
                .multilineTextAlignment(.center)
                .fixedSize(horizontal: false, vertical: true)
            HStack(spacing: 10) {
                Slider(value: Binding(get: { engine.freqScale },
                                      set: { engine.setFreqScale($0) }), in: 0.7...2.2)
                    .frame(width: 260)
                Text(String(format: "%.2f", engine.freqScale))
                    .font(.caption.monospacedDigit()).foregroundStyle(.secondary)
            }
            Button(L("Continue")) { onDone() }
                .buttonStyle(.borderedProminent)
        }
        .modifier(OnboardCard())
        // the guide voice loops from straight ahead the whole step — the fit is
        // right when it sits out in front, so ahead IS the reference
        .onAppear { engine.onboardPlay("fit", loop: true, bearingDeg: 0) }
        .onDisappear { engine.onboardStop() }
    }
}
