import type { AgentDef } from "./types";

/**
 * The agent roster. Order matters: demo mode keeps the first N, so the four
 * scripted-scenario personas (voices in public/audio/demo/, generated by
 * tools/gen-demo-voices.py) come first. Echo/Rook are extra seats for live mode.
 * repo/branch/cwd are the demo's plausible workspace identities — they flow into
 * the list rows the same way `task` seeds the title (live mode overwrites all of
 * this with real bind metadata).
 */
export const AGENTS: AgentDef[] = [
  { id: "atlas", name: "Atlas", color: "#7aa2ff", task: "refactoring auth",
    repo: "acme/auth-service", branch: "refactor/token-flow", cwd: "/Users/dev/work/auth-service" },
  { id: "wren", name: "Wren", color: "#5fd0c5", task: "db migration",
    repo: "acme/ledger", branch: "migrate/orders-schema", cwd: "/Users/dev/work/ledger" },
  { id: "cass", name: "Cass", color: "#ffce6b", task: "chasing a flake",
    repo: "acme/checkout", branch: "fix/flaky-cart-spec", cwd: "/Users/dev/work/checkout" },
  { id: "iris", name: "Iris", color: "#c08bff", task: "dependency upgrade",
    repo: "acme/web-app", branch: "chore/vite-6-upgrade", cwd: "/Users/dev/work/web-app" },
  { id: "echo", name: "Echo", color: "#9aa6b8", task: "baseline test",
    repo: "acme/search", branch: "test/baseline-relevance", cwd: "/Users/dev/work/search" },
  { id: "rook", name: "Rook", color: "#ff9d7a", task: "websocket reconnect",
    repo: "acme/gateway", branch: "fix/ws-reconnect", cwd: "/Users/dev/work/gateway" },
];

/** How many seats the scripted web demo uses (the first N of the roster). */
export const DEMO_AGENT_COUNT = 4;

/** Per-agent ping note — identity via pitch, a pentatonic-ish spread. */
export const PING_FREQS = [523.25, 392.0, 587.33, 659.25, 783.99, 880.0];

/** Seconds between pings for a done agent. */
export const PING_INTERVAL = 2.6;

/** Face a done agent this long (ms) to trigger its summary. */
export const LINGER_MS = 1500;

/** After a summary is heard, recycle the agent back to working after this long,
 *  so the standalone experience stays perpetually alive. */
export const RECYCLE_MS = 45000;

/** Random gap between an agent finishing on its own (relaxed cadence). */
export const AUTO_FINISH_MIN_MS = 27000;
export const AUTO_FINISH_MAX_MS = 66000;

/** How long after the last sign of life (tool call / narration) "working" keeps
 *  humming its drone before reading as idle. // mirrors AntiphonEngine.swift droneHoldSecs */
export const DRONE_HOLD_MS = 45000;
// eyes-closed gaze dwell before the hum crests, counted only in-scene
// (mirrors AntiphonEngine.swift dwellSecs = 1.0)
export const DWELL_MS = 1000;
/** Blink filter: eyes must stay closed this long before the scene comes in — a
 *  blink that happens to point at an agent must not start a dwell. Native makes
 *  this user-adjustable (immersion.fadeDelay, default 0.6 s); the web has no
 *  settings UI, so it's a constant. // mirrors AntiphonEngine.swift fadeDelaySecs */
export const FADE_DELAY_MS = 600;
// a given agent's dwell hum sounds at most this often (presence reminder)
export const BLOOM_COOLDOWN_MS = 30000;

/** Draggable-agent distance clamp: too close is deafening (the 0.45 m bubble);
 *  the outer bound is the ROOM's walls (queried from the wasm engine), because
 *  beyond them the reverb model no longer matches and voices go flat. DRAG_MAX_M
 *  is only the fallback ring while the room dims are still in flight.
 *  // mirrors AntiphonEngine.swift place(seat:) */
export const DRAG_MIN_M = 0.45;
export const DRAG_MAX_M = 2.6;
/** Keep dragged agents off the walls — image sources misbehave at 0. */
export const WALL_MARGIN_M = 0.35;
