import { DEMO_AGENT_COUNT } from "../agents";
import type { Chamber } from "../audio/engine";

// The scripted demo scenario: exactly the native experience, no talk-back.
// A small roster of agents works audibly — the working drone hums, tool-note
// ticks land every few seconds, and an occasional spoken murmur narrates what
// each is doing — and over time they complete tasks: done ping → you face one
// and linger → accept chime → a SPOKEN summary. Heard agents recycle back to
// working (the engine's RECYCLE_MS) and later complete again with a different
// line, so the room stays perpetually, believably alive.
//
// Voices live in public/audio/demo/<id>_{work,done}_<n>.mp3, generated by
// tools/gen-demo-voices.py — keep LINES below in sync with that script so the
// agent list shows exactly what was said.

interface AgentLines {
  work: string[];
  done: string[];
}

/** Mirror of tools/gen-demo-voices.py — the text of each generated clip. */
const LINES: Record<string, AgentLines> = {
  atlas: {
    work: [
      "Tracing every call site of the old session middleware.",
      "Rewriting the token refresh path now.",
    ],
    done: [
      "The auth refactor is in. Sessions refresh tokens in one place now, and the old middleware is gone.",
      "I split the login flow out of the monolith. Twelve files touched, all tests green.",
      "Password reset goes through the same token service now. I removed about four hundred lines.",
    ],
  },
  wren: {
    work: [
      "Backfilling the new columns in batches.",
      "Dry-running the migration against a staging snapshot.",
    ],
    done: [
      "The migration ran clean. Both tables are on the new schema, and the backfill finished in under a minute.",
      "I split the migration into three reversible steps. Staging is migrated; production is ready when you are.",
      "Indexes are rebuilt and the slow query is gone. Reads are about six times faster.",
    ],
  },
  cass: {
    work: [
      "Running the integration suite again to reproduce it.",
      "Bisecting the test order to find the leak.",
    ],
    done: [
      "Found the flake. A shared fixture leaked a timer between tests; it's isolated now, and the suite passed ten runs in a row.",
      "The race was in the websocket teardown. I made close idempotent and the suite is stable again.",
      "Two flaky tests were sharing a temp directory. They each get their own now, and CI is green.",
    ],
  },
  iris: {
    work: [
      "Reading the changelog for breaking changes.",
      "Bumping the lockfile and rebuilding.",
    ],
    done: [
      "The dependency upgrade is done. Two breaking changes patched, and the bundle came out smaller.",
      "Everything is on the latest major now. I pinned the one package that broke and left a note about it.",
      "Docs are updated to match the new API. Every example compiles again.",
    ],
  },
};

// ---- cadence (ms) -----------------------------------------------------------
const TICK_MS = 400;
const TOOL_MIN = 4000, TOOL_MAX = 11000; // tool-note ticks while working
const TOOL_FIRST_MAX = 8000;
const MURMUR_MIN = 30000, MURMUR_MAX = 55000; // spoken working murmurs
const FIRST_DONE_MIN = 14000, FIRST_DONE_MAX = 20000; // first completion lands early
const DONE_GAP_MIN = 20000, DONE_GAP_MAX = 40000; // staggered completions
const MAX_WAITING = 2; // never more than this many unheard dings at once
const RETRY_MS = 6000; // completion scheduler backoff when the room is saturated

const between = (a: number, b: number) => a + Math.random() * (b - a);

interface Seat {
  idx: number;
  id: string;
  workBufs: (AudioBuffer | null)[];
  doneBufs: (AudioBuffer | null)[];
  workIdx: number; // rotates through the murmur lines
  doneIdx: number; // rotates through the summary lines
  toolNext: number;
  murmurNext: number;
  lastDoneAt: number; // for least-recently-completed picking
  prevState: string;
}

/**
 * Load the scenario voices and start driving the engine. Returns a stop()
 * for symmetry (the demo page never calls it).
 */
export async function startScenario(engine: Chamber): Promise<() => void> {
  const count = Math.min(DEMO_AGENT_COUNT, engine.agents.length);
  const t0 = performance.now();

  // decode every clip up front; a missing/failed clip degrades gracefully
  // (that murmur is skipped / the summary falls back to the quiet acknowledge)
  const dec = (url: string): Promise<AudioBuffer | null> =>
    engine.loadClip(url).catch(() => null);
  const seats: Seat[] = await Promise.all(
    engine.agents.slice(0, count).map(async (a, idx) => {
      const lines = LINES[a.id] ?? { work: [], done: [] };
      const [workBufs, doneBufs] = await Promise.all([
        Promise.all(lines.work.map((_, n) => dec(`audio/demo/${a.id}_work_${n + 1}.mp3`))),
        Promise.all(lines.done.map((_, n) => dec(`audio/demo/${a.id}_done_${n + 1}.mp3`))),
      ]);
      return {
        idx,
        id: a.id,
        workBufs,
        doneBufs,
        workIdx: Math.floor(Math.random() * Math.max(1, lines.work.length)),
        doneIdx: 0,
        // stagger the room: everyone shows a first sign of life within seconds,
        // murmurs fan out so two voices don't speak over each other at the top
        toolNext: t0 + between(1500, TOOL_FIRST_MAX),
        murmurNext: t0 + 7000 + idx * 9000 + between(0, 6000),
        lastDoneAt: 0,
        prevState: "working",
      };
    }),
  );

  engine.startScripted(); // fade the room in; no random auto-finishing

  let nextDone = t0 + between(FIRST_DONE_MIN, FIRST_DONE_MAX);

  const tick = () => {
    const now = performance.now();
    let waiting = 0;
    for (const s of seats) {
      const N = engine.nodes[s.id];
      if (!N) continue;
      const state = N.state;
      if (state === "done" || state === "summarizing") waiting++;

      // recycled back to working (the engine did it) → re-stagger its life
      if (state === "working" && s.prevState !== "working") {
        s.toolNext = now + between(2000, TOOL_FIRST_MAX);
        s.murmurNext = now + between(9000, 25000);
      }
      s.prevState = state;
      if (state !== "working" || N.snoozed) continue;

      // tool-note ticks: the audible texture of an agent at work (also feeds
      // lastActivity, which keeps the working drone humming)
      if (now >= s.toolNext) {
        s.toolNext = now + between(TOOL_MIN, TOOL_MAX);
        engine.bridgeTool(s.idx);
      }
      // occasional spoken murmur — live-narration style one-shot through the
      // whisper mix (clear when faced, breathy in the ambient bed)
      if (now >= s.murmurNext) {
        s.murmurNext = now + between(MURMUR_MIN, MURMUR_MAX);
        const lines = LINES[s.id]?.work ?? [];
        if (lines.length) {
          const n = s.workIdx % lines.length;
          s.workIdx++;
          const buf = s.workBufs[n];
          engine.bridgeLine(s.idx, "progress", lines[n]);
          if (buf) engine.enqueueProgress(s.idx, buf);
        }
      }
    }

    // completions: staggered, one at a time, never flooding the room
    if (now >= nextDone) {
      if (waiting >= MAX_WAITING) {
        nextDone = now + RETRY_MS; // the user isn't listening — don't pile on
      } else {
        // least-recently-completed working agent finishes next
        const cand = seats
          .filter((s) => engine.nodes[s.id]?.state === "working" && !engine.nodes[s.id]?.snoozed)
          .sort((a, b) => a.lastDoneAt - b.lastDoneAt)[0];
        if (cand) {
          const lines = LINES[cand.id]?.done ?? [];
          const n = lines.length ? cand.doneIdx % lines.length : 0;
          cand.doneIdx++;
          cand.lastDoneAt = now;
          const buf = cand.doneBufs[n] ?? null;
          if (buf) engine.setSummaryClip(cand.idx, buf);
          if (lines[n]) engine.bridgeLine(cand.idx, "done", lines[n]);
          engine.markDone(cand.idx);
          nextDone = now + between(DONE_GAP_MIN, DONE_GAP_MAX);
        } else {
          nextDone = now + RETRY_MS; // everyone's mid-report; try again shortly
        }
      }
    }
  };

  const timer = window.setInterval(tick, TICK_MS);
  return () => window.clearInterval(timer);
}
